A = float(input("Introduce el valor de la variable A: "))
B = float(input("Introduce el valor de la variable B: "))
print("Uso de operadores lógicos")
print("A==B", A==B)
print("A!=B", A!=B)
print("A>B", A>B)
print("A<B", A<B)
print("A>=B", A>=B)
print("A<=B", A<=B)
print("A<=B", A<=B)
print("Uso de not, and y or")
print("not (A==B)", not (A==B))
print("(A==B) and (A!=B)", (A==B) and (A!=B))
print("(A==B) or (A!=B)", (A==B) or (A!=B))
print("(A>=B) or (A<B)", (A>=B) or (A<B))
